[package]
name = "diffhtml-rust-parser"
version = "1.0.0-beta.29"
edition = "2021"

[lib]
name = "parser"
path = "src/parser.rs"
test = false
bench = false
crate-type = ["cdylib"]

[dependencies]
tl = { version = "0.7.7", features = ["simd"] }
wasm-bindgen = { version = "0.2.83", features = [] }
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.60"

[profile.release]
strip = "symbols"
lto = true
opt-level = 3
